In [1]:
import numpy as np
import einops
import torch
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
from lerobot.datasets.lerobot_dataset import HF_LEROBOT_HOME
from lerobot.datasets.lerobot_dataset import LeRobotDataset

repo_id = "flow929/ledataset_libero_10"
root = HF_LEROBOT_HOME / repo_id


def parse_image(image):
    image = np.asarray(image)
    if np.issubdtype(image.dtype, np.floating):
        image = (255 * image).astype(np.uint8)
    if image.shape[0] == 3:
        image = einops.rearrange(image, "c h w -> h w c")
    return image

class MyPiDataset(Dataset):
    def __init__(self, base_ds):
        self.base_ds = base_ds

    def __len__(self):
        return len(self.base_ds)

    def __getitem__(self, idx):
        sample = self.base_ds[idx]

        out = {
            "state": sample["state"],
            "image": {
                "base_0_rgb": parse_image(sample["image"]),
                "left_wrist_0_rgb": parse_image(sample["wrist_image"]),
                "right_wrist_0_rgb": np.zeros_like(parse_image(sample["image"])),
            },
            "image_mask": {
                "base_0_rgb": True,
                "left_wrist_0_rgb": True,
                "right_wrist_0_rgb": False,
            },
            "actions": sample["actions"],
            "prompt": sample["task"],
        }
        return out
    

print("dataset root:", root)
print("exists:", root.exists())

for p in sorted(root.iterdir()):
    print(p.name)

ds = LeRobotDataset(repo_id)
my_ds = MyPiDataset(ds)

loader = DataLoader(
    my_ds,
    batch_size=4,
    shuffle=True,
    num_workers=0,
)

batch = next(iter(loader))
print(batch.keys())
print(batch["state"].shape)
print(batch["actions"].shape)

print(batch["image"]["base_0_rgb"].shape)
print(batch["image"]["left_wrist_0_rgb"].shape)
print(batch["image"]["right_wrist_0_rgb"].shape)

print(batch["image_mask"]["base_0_rgb"])
print(batch["image_mask"]["left_wrist_0_rgb"])
print(batch["image_mask"]["right_wrist_0_rgb"])
print(batch["prompt"][0])

/home/flow/code/mypi/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


dataset root: /home/flow/.cache/huggingface/lerobot/flow929/ledataset_libero_10
exists: True
data
images
meta
dict_keys(['state', 'image', 'image_mask', 'actions', 'prompt'])
torch.Size([4, 8])
torch.Size([4, 7])
torch.Size([4, 256, 256, 3])
torch.Size([4, 256, 256, 3])
torch.Size([4, 256, 256, 3])
tensor([True, True, True, True])
tensor([True, True, True, True])
tensor([False, False, False, False])
KITCHEN_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet_and_close_it_demo


In [2]:
print(batch["state"].shape)
print(batch["actions"].shape)
print(batch["prompt"][:2])

torch.Size([4, 8])
torch.Size([4, 7])
['KITCHEN_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet_and_close_it_demo', 'LIVING_ROOM_SCENE2_put_both_the_alphabet_soup_and_the_tomato_sauce_in_the_basket_demo']


In [3]:
import torch
import torch.nn.functional as F

def pad_last_dim(x, target_dim):
    cur_dim = x.shape[-1]
    if cur_dim > target_dim:
        raise ValueError(f"current dim {cur_dim} > target dim {target_dim}")
    if cur_dim == target_dim:
        return x
    pad = target_dim - cur_dim
    return F.pad(x, (0, pad), value=0)

batch2 = dict(batch)  # 浅拷贝先够用
batch2["state"] = pad_last_dim(batch["state"], 32)
batch2["actions"] = pad_last_dim(batch["actions"], 32)

print(batch2["state"].shape)
print(batch2["actions"].shape)

torch.Size([4, 32])
torch.Size([4, 32])


In [4]:
def resize_bhwc_uint8(images_bhwc, size=(224, 224)):
    # [B,H,W,C] -> [B,C,H,W]
    x = images_bhwc.permute(0, 3, 1, 2).float()
    x = F.interpolate(x, size=size, mode="bilinear", align_corners=False)
    x = x.round().clamp(0, 255).to(torch.uint8)
    # [B,C,H,W] -> [B,H,W,C]
    x = x.permute(0, 2, 3, 1)
    return x


In [5]:
batch2["image"] = {
    "base_0_rgb": resize_bhwc_uint8(batch["image"]["base_0_rgb"]),
    "left_wrist_0_rgb": resize_bhwc_uint8(batch["image"]["left_wrist_0_rgb"]),
    "right_wrist_0_rgb": resize_bhwc_uint8(batch["image"]["right_wrist_0_rgb"]),
}

print(batch2["image"]["base_0_rgb"].shape, batch2["image"]["base_0_rgb"].dtype)
print(batch2["image"]["left_wrist_0_rgb"].shape, batch2["image"]["left_wrist_0_rgb"].dtype)
print(batch2["image"]["right_wrist_0_rgb"].shape, batch2["image"]["right_wrist_0_rgb"].dtype)

torch.Size([4, 224, 224, 3]) torch.uint8
torch.Size([4, 224, 224, 3]) torch.uint8
torch.Size([4, 224, 224, 3]) torch.uint8


In [6]:
def task_to_prompt(task: str) -> str:
    s = task
    if s.endswith("_demo"):
        s = s[:-5]
    parts = s.split("_")
    # 去掉场景前缀，保留动作部分
    # 例如 LIVING_ROOM_SCENE6_put_the_white_mug... -> put the white mug ...
    action_start = 0
    for i, p in enumerate(parts):
        if p in ("put", "open", "close", "turn", "pick", "place", "move", "push", "pull", "stack"):
            action_start = i
            break
    s = " ".join(parts[action_start:])
    return s

clean_prompts = [task_to_prompt(p) for p in batch["prompt"]]
print(clean_prompts[0])

put the black bowl in the bottom drawer of the cabinet and close it


In [7]:
batch
for p in batch["prompt"]:
    p =task_to_prompt(p) 

In [8]:
batch

{'state': tensor([[-2.0521e-01,  8.9840e-05,  1.1789e+00,  3.1403e+00,  4.2798e-03,
          -9.0145e-02,  3.9300e-02, -3.9301e-02],
         [-9.3982e-02,  2.8425e-02,  5.6360e-01,  3.1016e+00, -5.2375e-01,
          -6.0080e-02,  3.8468e-02, -3.8433e-02],
         [ 1.0001e-01,  4.6099e-02,  6.8430e-01,  3.0815e+00, -1.8435e-01,
          -1.8538e-01,  2.0942e-02, -2.1804e-02],
         [-1.9801e-01,  1.7974e-01,  9.5320e-01,  2.5655e+00,  1.7481e+00,
          -3.6136e-02,  1.9473e-02, -2.5806e-02]]),
 'image': {'base_0_rgb': tensor([[[[200, 182, 162],
            [200, 182, 162],
            [199, 181, 161],
            ...,
            [198, 181, 165],
            [197, 180, 164],
            [197, 180, 164]],
  
           [[200, 182, 162],
            [199, 181, 161],
            [199, 181, 161],
            ...,
            [198, 181, 165],
            [197, 180, 164],
            [197, 180, 164]],
  
           [[199, 181, 161],
            [198, 180, 160],
            [199, 

In [9]:
sample = my_ds[0].copy()

# 1) prompt
if "prompt" not in sample:
    sample["prompt"] = sample["task"] if "task" in sample else "do the task"

# 2) resize
resize_tf = ResizeImages(224, 224)
sample = resize_tf(sample)

# 3) tokenize
tok_tf = TokenizePrompt(_tokenizer.PaligemmaTokenizer(None))
sample = tok_tf(sample)

# 4) pad
pad_tf = PadStatesAndActions(32)
sample = pad_tf(sample)

print(sample.keys())
print("state:", sample["state"].shape, sample["state"].dtype)
print("actions:", sample["actions"].shape, sample["actions"].dtype)
print("base image:", sample["image"]["base_0_rgb"].shape, sample["image"]["base_0_rgb"].dtype)
print("left wrist:", sample["image"]["left_wrist_0_rgb"].shape, sample["image"]["left_wrist_0_rgb"].dtype)
print("right wrist:", sample["image"]["right_wrist_0_rgb"].shape, sample["image"]["right_wrist_0_rgb"].dtype)
print("tokenized_prompt:", sample["tokenized_prompt"].shape, sample["tokenized_prompt"].dtype)
print("tokenized_prompt_mask:", sample["tokenized_prompt_mask"].shape, sample["tokenized_prompt_mask"].dtype)

NameError: name 'ResizeImages' is not defined